* pilot.d - what the D6 pilot's translations share (docs/status.md, "D6 pilot").
*
* The data area holds the arcade's 2K of RAM page for page: U = its base, DP = its page, so a
* zero-page variable is <name and anything else is name,U.  Both stay put for the whole game.
* arcade.d (generated by tools/d6pilot.py from the MAC65 source) gives the arcade addresses.

	opt	c			cycle counts in the listing (the harness checks its table)

* Pseudo-registers, in zero-page bytes the arcade never allocates ($B8-$BC; ALCOMN.MAC:685-687
* leaves them between SECUVG and the EAROM's $BD).  RXP and RYP are pointers: the high byte is
* the data area's page, set once at start-up, and the low byte is the 6502 register, so
* "ldx <RXP" is the data area base + X in one load.
RXP	equ	$B8		page of the data area
RX	equ	$B9		6502 X (model B; model A keeps X in B and uses RX only in passing)
RYP	equ	$BA		page of the data area
RY	equ	$BB		6502 Y (both models)

* Port variables past the arcade's RAM.
POKIMG	equ	$0800		POKEY register image: AUDF1,AUDC1..AUDF4,AUDC4 of POKEY 1, then POKEY 2

* The integer coprocessor (D8, approved absolute exception): 16/16 unsigned divide.
* JR_Math_Block.v: divisor $FEE4-5, dividend $FEE6-7, quotient $FEF4-5, all big-endian.
CP.DVSR	equ	$FEE4
CP.DVND	equ	$FEE6
CP.QUOT	equ	$FEF4
