#!/usr/bin/env python3
"""avgtest.py - the 6809 AVG interpreter (src/avg.a) against its specification (avgview.PortAVG).

Assembles src/avg.a with src/avgtab.a and the vector ROM into src/build/ (a wrapper, with a test
AvgFlush that hands each record batch to the harness), then runs AvgRun on the host 6809
(tools/cpu6809.py) over avgcap.lua captures, frame by frame, and compares with PortAVG:

  - every line record, in order, byte for byte (batches of at most 255, each from the buffer's start);
  - every text entry, and the count;
  - whether the list ended (HALT, JMPL 0) or was cut off as a runaway.

Frames alternate between two layouts (module, data area and window A all moved), so an absolute
address shows.  Reports the interpreter's cycles a frame, and milliseconds at 8 MHz.  The
coprocessor's multiplier is modelled as the RTL has it (combinational); --sw builds the software
multiply instead (AVGSWM).  Every coprocessor access must come with interrupts masked.

--fuzz N runs N random display lists instead (every binary scale, components big and tiny, short
vectors, characters at any scale, subroutines in RAM, beams far off the bitmap), against the same
specification.

Usage:
  avgtest.py CAPTURE... [--every N] [--limit N] [--first 600] [--sw] [--quiet]
  avgtest.py --fuzz N [--seed S] [--sw]
"""

import argparse
import os
import random
import struct
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
import avgview as av  # noqa: E402
from cpu6809 import CPU6809  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "src")
BUILD = os.path.join(SRC, "build")

FLUSH_PORT = 0xFFE2
AVGPG = 0x0C00
VWIN = 0x0810
# (module, data area, window A): the second moves all three, the module off a page boundary.
LAYOUTS = [(0x8000, 0x1000, 0x4000), (0x9321, 0x2300, 0x6000)]
OFF = {"TCNT": 51, "END": 55, "JMP": 53, "RMAX": 113, "WNC": 125, "WOVF": 126, "WENA": 129}
WELL = False               # --well: the well captured (AVWELL; PortAVG well=True)
BATCH_RANDOM = False       # --batch 0: AvgFlush sets a random size for the next batch each time

WRAPPER = """* avgtest.a - GENERATED by tools/avgtest.py: src/avg.a with a test AvgFlush.
\topt\tc
\tinclude\tport.d
ModBeg\tequ\t*
\tinclude\tavg.a
\tinclude\tavgtab.a
VROM\tincludebin\tvrom.bin
* The test's AvgFlush: the batch (X, B) to the harness, through a write it watches.
AvgFlush\ttstb\t\t\t(AVWELL: 0 when the batch held only the well's room)
\tbeq\t_AFz
\tstb\t$%04X
_AFz\trts
""" % FLUSH_PORT


def build(sw=False, batch=None, collapse=False, well=False):
    os.makedirs(BUILD, exist_ok=True)
    wrap = os.path.join(BUILD, "avgtest.a")
    open(wrap, "w").write(WRAPPER)
    binp, lst = os.path.join(BUILD, "avgtest.bin"), os.path.join(BUILD, "avgtest.lst")
    r = subprocess.run(["lwasm.orig", "--6809", "--format=raw", "--pragma=nosymbolcase", "-I", SRC,
                        "-o", binp, "--list=" + lst, "--symbols", wrap] + (["-DAVGSWM"] if sw else []) +
                       (["-DRBATCH=%d" % batch] if batch else []) + (["-DAVCOLL"] if collapse else []) +
                       (["-DAVWELL"] if well else []),
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit((r.stdout + r.stderr)[:4000] + "\nsrc/avg.a does not assemble")
    labels = {}
    for line in open(lst):
        if line.startswith("[ G]"):
            name, val = line[4:].split()
            labels[name] = int(val, 16)
    return open(binp, "rb").read(), labels


def s16(v):
    return v - 0x10000 if v & 0x8000 else v


class Rig:
    def __init__(self, code, labels, layout):
        self.mod, self.data, self.win = layout
        self.cpu = CPU6809()
        self.cpu.load(self.mod, code)
        self.entry = self.mod + labels["AvgRun"]
        self.rbuf = self.win + 0x1000
        self.cpu.map_io(FLUSH_PORT, FLUSH_PORT, write=self.flush)
        self.cp = bytearray(32)
        self.cpu.map_io(0xFEE0, 0xFEFF, self.cp_read, self.cp_write)

    def cp_check(self, a):
        if not self.cpu.cc & 0x10:
            self.errors.append("coprocessor %04X touched with IRQ unmasked" % a)

    def cp_read(self, a):
        self.cp_check(a)
        return self.cp[a - 0xFEE0]

    def cp_write(self, a, v):
        self.cp_check(a)
        r = self.cp
        r[a - 0xFEE0] = v
        p = (r[0] << 8 | r[1]) * (r[2] << 8 | r[3])
        r[0x10:0x14] = p.to_bytes(4, "big")

    def flush(self, addr, value):
        cpu = self.cpu
        n = value & 0xFF
        if cpu.x != self.rbuf:
            self.errors.append("a batch from %04X, not the buffer's start %04X" % (cpu.x, self.rbuf))
        if not 1 <= n <= 255:
            self.errors.append("a batch of %d records" % n)
        if cpu.u != self.data or cpu.dp != self.data >> 8:
            self.errors.append("AvgFlush called with U %04X DP %02X" % (cpu.u, cpu.dp))
        for k in range(n):
            b = cpu.mem[cpu.x + 8 * k:cpu.x + 8 * k + 8]
            if b[7]:
                self.errors.append("a record's reserved byte is %02X" % b[7])
            self.recs.append((s16(b[0] << 8 | b[1]), b[4], s16(b[2] << 8 | b[3]), b[5], b[6]))
        rmax = cpu.mem[self.data + AVGPG + OFF["RMAX"]]
        if n > rmax:
            self.errors.append("a batch of %d records where the size was %d" % (n, rmax))
        if BATCH_RANDOM:
            cpu.mem[self.data + AVGPG + OFF["RMAX"]] = random.randrange(1, 256)

    def run(self, vram):
        cpu = self.cpu
        self.recs, self.errors = [], []
        cpu.mem[self.win:self.win + 4096] = vram
        cpu.mem[self.win + 4096:self.win + 8192] = bytes([0xA5]) * 4096
        cpu.mem[self.data:self.data + 0x2000] = bytes([0x5A]) * 0x2000
        struct.pack_into(">H", cpu.mem, self.data + VWIN, self.win)
        cpu.mem[self.data + AVGPG + OFF["RMAX"]] = random.randrange(1, 256) if BATCH_RANDOM else 0
        cpu.mem[self.data + AVGPG + OFF["WENA"]] = 1 if WELL else 0
        cpu.u = self.data
        cpu.dp = 0x77
        cpu.s = self.data + 0x1F00
        cpu.a = cpu.b = cpu.x = cpu.y = 0
        cycles = cpu.call(self.entry, limit=20_000_000)
        if cpu.u != self.data or cpu.dp != 0x77 or cpu.s != self.data + 0x1F00:
            self.errors.append("U, DP or S not kept")
        pg = self.data + AVGPG
        ntxt = cpu.mem[pg + OFF["TCNT"]] << 8 | cpu.mem[pg + OFF["TCNT"] + 1]
        texts = []
        t0 = self.win + 0x1800
        for k in range(min(ntxt, 300)):
            b = cpu.mem[t0 + 6 * k:t0 + 6 * k + 6]
            texts.append((b[0], b[1], s16(b[2] << 8 | b[3]), s16(b[4] << 8 | b[5])))
        self.wrecs, self.wovf = [], 0
        if WELL:
            w0 = self.win + 0x1E00
            for k in range(cpu.mem[pg + OFF["WNC"]]):
                b = cpu.mem[w0 + 8 * k:w0 + 8 * k + 8]
                if b[7]:
                    self.errors.append("a well record's reserved byte is %02X" % b[7])
                self.wrecs.append((s16(b[0] << 8 | b[1]), b[4], s16(b[2] << 8 | b[3]), b[5], b[6]))
            self.wovf = cpu.mem[pg + OFF["WOVF"]]
        return cycles, texts, cpu.mem[pg + OFF["END"]]


def word(w):
    return bytes((w & 0xFF, (w >> 8) & 0xFF))


def random_list(rng, rom, shapes=(), well=False):
    """A random display list at vector RAM 0, with a subroutine at $400 (words), ending JMPL 0.
    Half the lists are dot-heavy: zero vectors, two colours, and jumps that leave the beam just
    off an edge of the bitmap (the redundant-dot rule and the clip meeting)."""
    chars = [av.vg_word(bytes(4096) + rom, av.VGMSGA_W + i) & 0x1FFF for i in range(av.NGLYPHS)]
    dots = rng.random() < 0.5

    def comp():
        k = rng.random()
        if dots and k < 0.45:
            return 0
        if k < 0.15:
            return rng.choice((0, 0x1FFF, 1, 0x1FFE))              # 0, -1, 1, -2
        if k < 0.3:
            return rng.randrange(0x2000)                          # anything, n < 3 included
        if dots and k < 0.4:
            return rng.randrange(-900, 900) & 0x1FFF              # to an edge and past it
        return rng.randrange(-600, 600) & 0x1FFF

    def body(n, sub):
        out = b""
        for _ in range(n):
            k = rng.random()
            if k < 0.35:
                z = rng.choice((0, 1, 6, 6)) if dots else rng.randrange(8)
                out += word(comp()) + word((z << 13) | comp())                          # VCTR
            elif k < 0.5:
                out += word(0x4000 | rng.randrange(0x2000))                             # SVEC
            elif k < 0.6:
                bs = rng.randrange(8)
                lin = rng.choice((0, 0, rng.randrange(256)))
                out += word(0x7000 | (bs << 8) | lin)                                   # SCAL
            elif k < 0.68:
                if dots:
                    out += word(0x6800 | rng.choice((3, 5)))                            # colour
                else:
                    out += word(0x6000 | rng.randrange(0x1000))                         # STAT
            elif k < 0.72:
                out += word(0x8040)                                                     # CNTR
            elif dots and k < 0.78:
                d = rng.randrange(200, 1200)                  # out through the top or bottom and
                d = (d if rng.random() < 0.5 else -d) & 0x1FFF  # back: a dot off, a dot back on
                out += (word(d) + word(0) + word(0) + word(6 << 13) +
                        word(-av.sext(d, 13) & 0x1FFF) + word(0) + word(0) + word(6 << 13))
            elif k < 0.85:
                if shapes and rng.random() < 0.5:                  # a small shape (--collapse), at
                    bs = rng.choice((0, 1, 2, 3, 4, 5, 6, 7))       # a scale that may collapse it
                    out += word(0x7000 | (bs << 8) | rng.choice((0, rng.randrange(256), 0xFF)))
                    if rng.random() < 0.3:
                        out += word(0x6000 | rng.randrange(0x1000))                     # STAT
                    out += word(0xA000 | rng.choice(shapes))
                else:
                    out += word(0xA000 | rng.choice(chars))                             # a character
            elif k < 0.9 and not sub:
                if well and rng.random() < 0.5:
                    out += word(0xA000 | 0x205)                                         # the well
                else:
                    out += word(0xA000 | (0x600 if well else 0x400))                    # the subroutine
            else:
                out += word(comp()) + word((1 << 13) | comp())                          # VCTR, Z = 1
        return out
    if not well:
        main = body(rng.randrange(5, 120), False) + word(0xE000)
        sub = body(rng.randrange(1, 30), True) + word(0xC000)                           # RTSL
        vram = bytearray(4096)
        vram[:len(main)] = main[:0x800]
        vram[0x800:0x800 + len(sub)] = sub
        return bytes(vram)
    # --well: the main list below word $205, the well (sometimes long enough to fill the capture)
    # at $205, the other subroutine at $600
    main = body(rng.randrange(5, 50), False)[:0x400] + word(0xE000)
    wsub = body(rng.choice((rng.randrange(1, 30), rng.randrange(40, 90))), True)[:0x3F0] + word(0xC000)
    sub = body(rng.randrange(1, 30), True)[:0x3F0] + word(0xC000)
    vram = bytearray(4096)
    vram[:len(main)] = main
    vram[0x40A:0x40A + len(wsub)] = wsub
    vram[0xC00:0xC00 + len(sub)] = sub
    return bytes(vram)


def fuzz(a, code, labels):
    import random
    rng = random.Random(a.seed)
    rigs = [Rig(code, labels, lay) for lay in LAYOUTS]
    rom = open(os.path.join(SRC, "vrom.bin"), "rb").read()
    port = av.PortAVG(rom, collapse=a.collapse, well=a.well)
    shapes = sorted(port.shapes) if a.collapse else ()
    ovfs = 0
    fails = 0
    collapsed = 0
    for i in range(a.fuzz):
        vram = random_list(rng, rom, shapes, a.well)
        rig = rigs[i % 2]
        recs, texts = port.run(vram)
        collapsed += port.stats["collapsed"]
        _, gtexts, ended = rig.run(vram)
        bad = list(rig.errors)
        if rig.recs != [tuple(r) for r in recs]:
            j = next((j for j, (p, q) in enumerate(zip(rig.recs, recs)) if p != tuple(q)),
                     min(len(rig.recs), len(recs)))
            bad.append("records: %d, want %d; first difference at %d: %s, want %s" %
                       (len(rig.recs), len(recs), j, rig.recs[j:j + 1], recs[j:j + 1]))
        if gtexts != texts:
            bad.append("texts differ (%d, want %d)" % (len(gtexts), len(texts)))
        if ended != port.stats["ended"]:
            bad.append("ended %d, want %d" % (ended, port.stats["ended"]))
        if a.well:
            ovfs += port.wovf
            if rig.wrecs != [tuple(r) for r in port.wrecs] or bool(rig.wovf) != port.wovf:
                bad.append("well: %d records (overflow %d), want %d (%s)" %
                           (len(rig.wrecs), rig.wovf, len(port.wrecs), port.wovf))
        if bad:
            fails += 1
            if fails <= 10:
                print("FAIL case %d:" % i)
                for b in bad[:4]:
                    print("   ", b)
    print("fuzz: %d random lists, %d failed%s%s" % (a.fuzz, fails, (", %d shapes collapsed" % collapsed)
                                                    if a.collapse else "",
                                                    (", %d well overflows" % ovfs) if a.well else ""))
    sys.exit(1 if fails else 0)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("captures", nargs="*")
    ap.add_argument("--fuzz", type=int, default=0, help="random display lists instead of captures")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--every", type=int, default=1, help="every n-th captured frame")
    ap.add_argument("--limit", type=int, default=0, help="at most this many frames a capture")
    ap.add_argument("--first", type=int, default=600, help="skip MAME frames before this (power-up)")
    ap.add_argument("--sw", action="store_true", help="the software multiply (AVGSWM)")
    ap.add_argument("--batch", type=int, help="records a batch (RBATCH; the module's, not 255); 0 = a random"
                    " size set by AvgFlush for each next batch (AV.RMAX, as the module's AvgFlush does)")
    ap.add_argument("--collapse", action="store_true", help="small shapes collapsed (AVCOLL; PortAVG's"
                    " collapse=True)")
    ap.add_argument("--well", action="store_true", help="the well captured (AVWELL; PortAVG's well=True)")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()

    global BATCH_RANDOM, WELL
    BATCH_RANDOM = a.batch == 0
    WELL = a.well
    code, labels = build(a.sw, a.batch or None, a.collapse, a.well)
    print("avg.a: %d bytes of code, %d with the glyph tables (VROM excluded)" %
          (labels["AvGMap"] - labels["AvgRun"], labels["VROM"] - labels["AvgRun"]))
    if a.fuzz:
        fuzz(a, code, labels)
    rigs = [Rig(code, labels, lay) for lay in LAYOUTS]
    fails = 0
    allcyc = []
    for cap in a.captures:
        port = None
        cyc = []
        k = 0
        for item in av.read_capture(cap):
            if item[0] == "rom":
                port = av.PortAVG(item[1], collapse=a.collapse, well=a.well)
                continue
            _, n, vram, cram = item
            if n < a.first:
                continue
            k += 1
            if (k - 1) % a.every:
                continue
            if a.limit and len(cyc) >= a.limit:
                break
            rig = rigs[len(cyc) % 2]
            recs, texts = port.run(vram)
            cycles, gtexts, ended = rig.run(vram)
            cyc.append(cycles)
            want_recs = [(r[0], r[1], r[2], r[3], r[4]) for r in recs]
            bad = list(rig.errors)
            if rig.recs != want_recs:
                i = next((i for i, (p, q) in enumerate(zip(rig.recs, want_recs)) if p != q),
                         min(len(rig.recs), len(want_recs)))
                bad.append("records: %d, want %d; first difference at %d: %s, want %s" %
                           (len(rig.recs), len(want_recs), i, rig.recs[i:i + 1], want_recs[i:i + 1]))
            if gtexts != texts:
                i = next((i for i, (p, q) in enumerate(zip(gtexts, texts)) if p != q),
                         min(len(gtexts), len(texts)))
                bad.append("texts: %d, want %d; first difference at %d: %s, want %s" %
                           (len(gtexts), len(texts), i, gtexts[i:i + 1], texts[i:i + 1]))
            if ended != port.stats["ended"]:
                bad.append("ended %d, want %d" % (ended, port.stats["ended"]))
            if a.well and (rig.wrecs != [tuple(r) for r in port.wrecs] or bool(rig.wovf) != port.wovf):
                bad.append("well: %d records (overflow %d), want %d (%s)" %
                           (len(rig.wrecs), rig.wovf, len(port.wrecs), port.wovf))
            if bad:
                fails += 1
                if fails <= 10:
                    print("FAIL %s frame %d (layout %d):" % (os.path.basename(cap), n, (len(cyc) - 1) % 2))
                    for b in bad[:4]:
                        print("   ", b)
            elif not a.quiet and len(cyc) % 200 == 0:
                print("  %s: %d frames" % (os.path.basename(cap), len(cyc)), flush=True)
        allcyc += cyc
        report(os.path.basename(cap), cyc)
    if len(a.captures) > 1:
        report("all", allcyc)
    print("%d frames, %d failed" % (len(allcyc), fails))
    sys.exit(1 if fails else 0)


def report(name, cyc):
    if not cyc:
        return
    v = sorted(cyc)
    ms = lambda c: c / 8000.0
    print("%s: %d frames; cycles median %d (%.2f ms at 8 MHz), 95%% %d (%.2f ms), max %d (%.2f ms)" %
          (name, len(v), v[len(v) // 2], ms(v[len(v) // 2]), v[int(len(v) * 0.95)],
           ms(v[int(len(v) * 0.95)]), v[-1], ms(v[-1])))


if __name__ == "__main__":
    main()
