#!/usr/bin/env python3
"""d6pilot.py - the D6 pilot's differential test and measurements (docs/status.md, "D6 pilot").

Runs three of Atari's routines out of the Rev 3 ROM on a host 6502 (tools/cpu6502.py, with MAME's
Math Box model) and their 6809 translations (pilot/*.a, assembled by lwasm --6809) on a host 6809
(tools/cpu6809.py, with the F256 coprocessor's divide), on the same inputs, and compares every
output: the arcade RAM, vector RAM, the POKEY register image, and the 6502 registers A, X, Y.
Each 6809 case runs twice, at two code addresses and two data-area/window addresses, so a
position-dependent translation fails.  Reports size and cycles per routine and register model.

    d6pilot.py            build pilot/, run every test, print the tables
    d6pilot.py --defs     only regenerate pilot/arcade.d and pilot/sound.bin
"""

import argparse
import os
import random
import statistics
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
import m65parse                         # noqa: E402
import romfind                          # noqa: E402
from cpu6502 import CPU6502, MathBox, load_rev3     # noqa: E402
from cpu6809 import CPU6809, listing_cycles         # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
PILOT = os.path.join(ROOT, "pilot")
BUILD = os.path.join(PILOT, "build")
MHZ_6502 = 1.512
MHZ_6809 = 8.0

SYMS = """PYL EYL EYH PZL EZL PXL EXL MTEMP SZL SZH SXL SXH ZADJL XADJL
NCHANL SINDEX POINT CURRENT FRAMES COUNT STVAL FRCNT CHANGE NUMBER
NYMCOL COLOR MZCOLO NNYMPH INDEX1 NYMPY NYMPL LIFSZL LIFSZH LIFSXL LIFSXH QT1 WAVEN1 FRTIMR
VGLIST CURNTX CURNTY VGBRIT QSTATUS""".split()

# The 6809 memory layouts each case runs under: code, data area (page aligned), vector-RAM window.
CONFIGS = [dict(code=0x8000, data=0x1000, window=0x4000),
           dict(code=0xA1E7, data=0x5300, window=0x2000)]
STACK = 0x7F00
VGLIST = 0x74
PSEUDO = range(0xB8, 0xBC)          # RXP, RX, RYP, RY: the port's bytes, not the arcade's
STACK6502 = range(0x1D0, 0x200)     # the 6502's stack, where the harness's JSR lands


def syms():
    p = m65parse.Parser()
    for f in ("ALCOMN", "ALSOUN", "ALDIS2", "ALVGUT"):
        p.parse(os.path.join(p.srcdir, f + ".MAC"))
    return p.syms


def gen_defs(cpu):
    s = syms()
    with open(os.path.join(PILOT, "arcade.d"), "w") as f:
        f.write("* arcade.d - arcade symbols for the D6 pilot, generated by tools/d6pilot.py from the\n"
                "* MAC65 source (tools/m65parse.py).  Addresses are offsets into the data area.\n")
        for n in SYMS:
            f.write("%-8s equ $%04X\n" % (n, s[m65parse.sym6(n)]))
    # SOUND is where MODSND's first LDA Y,SOUND+STVAL points (opcode B9 abs,Y).
    addrs, _ = romfind.find("ALSOUN", "MODSND", 200, cpu)
    a = addrs["MODSND"]
    while cpu.mem[a] != 0xB9:
        a += 1
    sound = cpu.mem[a + 1] | cpu.mem[a + 2] << 8
    with open(os.path.join(PILOT, "sound.bin"), "wb") as f:
        f.write(bytes(cpu.mem[sound:sound + 0x204]))
    return sound


def assemble(src, out, defines=()):
    os.makedirs(BUILD, exist_ok=True)
    binp = os.path.join(BUILD, out + ".bin")
    lst = os.path.join(BUILD, out + ".lst")
    cmd = ["lwasm.orig", "--6809", "--format=raw", "--symbols", "-I", PILOT, "-o", binp,
           "--list=" + lst]
    cmd += ["-D%s" % d for d in defines]
    cmd.append(os.path.join(PILOT, src))
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        sys.exit("lwasm failed on %s:\n%s%s" % (src, r.stdout, r.stderr))
    code = open(binp, "rb").read()
    labels = {}
    for line in open(lst):
        # the --symbols table: "[ G] NAME        0012"
        if line.startswith("[ G]"):
            name, val = line[4:].split()
            labels[name] = int(val, 16)
    return code, labels, lst


class Rig:
    """One routine under one register model: the 6502 reference and the 6809 translation."""

    def __init__(self, cpu, model, code, labels, lst):
        self.ref = cpu
        self.model = model
        self.code = code
        self.labels = labels
        self.cyc_listing = listing_cycles(lst)
        self.cpus = []
        for cfg in CONFIGS:
            c = CPU6809()
            c.load(cfg["code"], code)
            c.cfg = cfg
            self.attach_coprocessor(c)
            self.cpus.append(c)
        self.checked = set()

    @staticmethod
    def attach_coprocessor(c):
        regs = bytearray(32)

        def wr(a, v):
            regs[a - 0xFEE0] = v
            den = regs[4] << 8 | regs[5]
            num = regs[6] << 8 | regs[7]
            q, r = (num // den, num % den) if den else (0xDEAD, 0xDEAD)   # undefined: make it loud
            regs[0x14], regs[0x15], regs[0x16], regs[0x17] = q >> 8, q & 0xFF, r >> 8, r & 0xFF

        c.map_io(0xFEE0, 0xFEFF, lambda a: regs[a - 0xFEE0], wr)

    def run6809(self, c, entry, arcade, vram, a, x, y):
        cfg = c.cfg
        d, w = cfg["data"], cfg["window"]
        c.mem[d:d + 0x800] = arcade
        c.mem[d + 0x800:d + 0x900] = bytes(0x100)
        c.mem[w:w + 0x1000] = vram
        # VGLIST: the arcade's little-endian $2xxx address becomes a big-endian logical one.
        va = arcade[VGLIST] | arcade[VGLIST + 1] << 8
        la = (va - 0x2000 + w) & 0xFFFF
        c.mem[d + VGLIST], c.mem[d + VGLIST + 1] = la >> 8, la & 0xFF
        c.mem[d + 0xB8] = c.mem[d + 0xBA] = d >> 8
        c.mem[d + 0xB9] = x
        c.mem[d + 0xBB] = y
        c.a, c.b = a, (x if self.model == "A" else random.randrange(256))
        c.x = c.y = random.randrange(0x10000)
        c.u, c.dp, c.s = d, d >> 8, STACK
        c.cc = 0x50
        cyc = c.call(cfg["code"] + self.labels[entry])
        out = bytearray(c.mem[d:d + 0x800])
        la = c.mem[d + VGLIST] << 8 | c.mem[d + VGLIST + 1]
        va = (la - w + 0x2000) & 0xFFFF
        out[VGLIST], out[VGLIST + 1] = va & 0xFF, va >> 8
        x_out = c.b if self.model == "A" else c.mem[d + 0xB9]
        return cyc, out, bytes(c.mem[w:w + 0x1000]), bytes(c.mem[d + 0x800:d + 0x810]), \
            (c.a, x_out, c.mem[d + 0xBB])

    def check_cycles(self, c):
        """Every executed 6809 instruction's cycle count against lwasm's --6809 listing."""
        base = c.cfg["code"]
        for pc, cyc in c.static.items():
            off = pc - base
            if off in self.checked or off not in self.cyc_listing:
                continue
            if c.mem[pc] != self.code[off]:
                continue                        # overwritten: reported by the caller's guard
            b, e, line = self.cyc_listing[off]
            want = b + e
            if cyc != want:
                raise AssertionError("cycle table: %04X is %d here, %d in the listing: %s" %
                                     (off, cyc, want, line))
            self.checked.add(off)

    def case(self, entry6502, entry6809, arcade, vram, a, x, y, pokey_io, compare_skip=()):
        ref = self.ref
        ref.mem[0:0x800] = arcade
        ref.mem[0x2000:0x3000] = vram
        ref.a, ref.x, ref.y, ref.sp = a, x, y, 0xFF
        ref.p = 0x24            # I set, binary mode, N Z V C clear: as the 6809 starts (CC = $50)
        pokey_io[:] = bytes(16)
        cyc65 = ref.call(entry6502)
        want = (bytes(ref.mem[0:0x800]), bytes(ref.mem[0x2000:0x3000]), bytes(pokey_io),
                (ref.a, ref.x, ref.y))
        results = []
        for c in self.cpus:
            cyc09, mem, vr, pk, regs = self.run6809(c, entry6809, arcade, vram, a, x, y)
            self.check_cycles(c)
            diffs = []
            for i in range(0x800):
                if i in PSEUDO or i in STACK6502 or i in compare_skip:
                    continue
                if mem[i] != want[0][i]:
                    diffs.append("RAM $%03X: 6809 %02X, 6502 %02X" % (i, mem[i], want[0][i]))
            for i in range(0x1000):
                if vr[i] != want[1][i]:
                    diffs.append("vector RAM $%04X: 6809 %02X, 6502 %02X" % (0x2000 + i, vr[i], want[1][i]))
            for i in range(16):
                if pk[i] != want[2][i]:
                    diffs.append("POKEY image %d: 6809 %02X, 6502 %02X" % (i, pk[i], want[2][i]))
            for n, g, w_ in zip("AXY", regs, want[3]):
                if g != w_:
                    diffs.append("register %s: 6809 %02X, 6502 %02X" % (n, g, w_))
            if diffs:
                return cyc65, None, diffs, c.cfg
            results.append(cyc09)
        if results[0] != results[1]:
            return cyc65, None, ["cycles differ between layouts: %s" % results], None
        return cyc65, results[0], [], None


def make_ref():
    cpu = load_rev3(CPU6502())
    mb = MathBox()
    mb.attach(cpu)
    pokey = bytearray(16)

    def pw(a, v):
        if 0x60C0 <= a <= 0x60C7:
            pokey[a - 0x60C0] = v
        elif 0x60D0 <= a <= 0x60D7:
            pokey[8 + a - 0x60D0] = v

    cpu.map_io(0x60C0, 0x60DF, None, pw)
    return cpu, mb, pokey


def inimat(mb):
    """The Math Box as INIMAT (ALDIS2.MAC:2368) leaves it, which is how WORSCR finds it."""
    mb.reg = [0] * 16
    mb.reg[6] = 0x0F


# --- test cases --------------------------------------------------------------------------------

def rand_arcade(rng):
    return bytearray(rng.randrange(256) for _ in range(0x800))


def cases_worscr(rng, n):
    s = syms()
    for k in range(n):
        m = rand_arcade(rng)
        kind = k % 8
        m[s["EYH"]] = rng.choice([0, 0, 0xFA, 0xFB, 0xFC, 0xFE, 0xFF, rng.randrange(256)])
        if kind == 0:                                   # DY = 0: the point level with the eye
            m[s["EYH"]] = 0
            m[s["PYL"]] = m[s["EYL"]]
        elif kind == 1:                                 # saturation: offsets near the ends
            for base in ("ZADJL", "XADJL"):
                v = rng.choice([0x7FF0, 0x8010, 0x7F00, 0x80FF, 0x0000, 0xFFFF])
                m[s[base]], m[s[base] + 1] = v & 0xFF, v >> 8
            m[s["EYH"]] = 0
            m[s["EYL"]] = (m[s["PYL"]] - rng.randrange(1, 4)) & 0xFF
        elif kind == 2:                                 # behind the eye
            m[s["EYH"]] = rng.randrange(1, 0x80)
        elif kind == 3:                                 # level with the eye in Z and in X
            m[s["PZL"]] = m[s["EZL"]]
            m[s["PXL"]] = m[s["EXL"]]
        yield m, bytes(0x1000), rng.randrange(256), rng.randrange(256), rng.randrange(256)


def cases_modsnd(rng, n):
    """Random channel states, each run once: every path, the 9-bit table half, odd/even X."""
    s = syms()
    for _ in range(n):
        m = rand_arcade(rng)
        for ch in range(16):
            m[s["POINT"] + ch] = rng.choice([0, rng.randrange(256), rng.randrange(1, 60)])
            m[s["FRAMES"] + ch] = rng.choice([1, 1, 2, rng.randrange(256)])
            m[s["COUNT"] + ch] = rng.choice([1, 1, 2, rng.randrange(256)])
        m[s["SINDEX"]] = rng.choice([0xFF, rng.randrange(16), rng.randrange(256)])
        yield m, bytes(0x1000), rng.randrange(256), rng.randrange(256), rng.randrange(256)


def cases_dspnym(rng, n):
    s = syms()
    for k in range(n):
        m = rand_arcade(rng)
        busy = rng.random()
        for i in range(64):
            m[s["NYMPY"] + i] = rng.randrange(1, 256) if rng.random() < busy else 0
            m[s["NYMPL"] + i] = rng.randrange(16)
        m[s["QT1"]] = rng.choice([0, 0, 0, rng.randrange(1, 256)])
        va = rng.randrange(0x2000, 0x2E00)
        m[VGLIST], m[VGLIST + 1] = va & 0xFF, va >> 8
        vram = bytes(rng.randrange(256) for _ in range(0x1000))
        yield m, vram, rng.randrange(256), rng.randrange(256), rng.randrange(256)


def sound_sequence(rig, fsndon, modsnd6502, rng, steps):
    """Play the game's sounds: start them with the ROM's FSNDON on the 6502, copy what it changed
    into the 6809's state, and step both MODSNDs in lockstep for `steps` IRQs."""
    s = syms()
    ref = rig.ref
    ref.mem[0:0x800] = bytes(0x800)
    for c in rig.cpus:
        d = c.cfg["data"]
        c.mem[d:d + 0x900] = bytes(0x900)
    cyc65, cyc09, fails = [], [], []
    for t in range(steps):
        if rng.random() < 0.02:
            before = bytes(ref.mem[0:0x100])
            ref.a = 16 * rng.randrange(13) + 15          # SIDxx = the sound's last PNTRS byte
            ref.sp = 0xFF
            ref.call(fsndon)
            after = bytes(ref.mem[0:0x100])
            for c in rig.cpus:
                d = c.cfg["data"]
                for i in range(0x100):
                    if before[i] != after[i] and i not in PSEUDO:
                        c.mem[d + i] = after[i]
        arcade = bytes(ref.mem[0:0x800])
        c65, c09, diffs, cfg = rig.case(modsnd6502, "MODSND", arcade, bytes(0x1000),
                                        ref.a, ref.x, ref.y, rig.pokey)
        if diffs:
            fails.append((t, diffs[:4]))
            break
        cyc65.append(c65)
        cyc09.append(c09)
    return cyc65, cyc09, fails


def summary(c65, c09):
    def st(v):
        return (min(v), statistics.median(v), statistics.mean(v), max(v))
    return st(c65), st(c09)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--defs", action="store_true")
    ap.add_argument("-n", type=int, default=2000, help="random cases per routine")
    ap.add_argument("--seed", type=int, default=1)
    a = ap.parse_args()

    ref, mb, pokey = make_ref()
    gen_defs(ref)
    if a.defs:
        return
    s = syms()

    where = {}
    for f, lab in (("ALDIS2", "WORSCR"), ("ALSOUN", "MODSND"), ("ALSOUN", "SNDON"),
                   ("ALDIS2", "DSPNYM"), ("ALVGUT", "VGRTSL"), ("ALDIS2", "VGYAB1")):
        addrs, end = romfind.find(f, lab, 400, ref)
        where.update(addrs)
        where[lab + "$end"] = end
    size65 = {
        "WORSCR": where["INIDSP"] - where["WORSCR"],
        "MODSND": where["INISOU"] - where["MODSND"],
        # DSPNYM, and the utilities translated with it: VGSTAT..VGSCAL less VGCNTR, VGYAB1..its JMP
        "DSPNYM": (where["VGDOT"] - where["DSPNYM"]) +
                  (where["VGVTR"] - where["VGSTAT"]) - (where["VGADD2"] - where["VGCNTR"]) +
                  (where["VGYAB1$end"] - where["VGYAB1"]),
    }

    builds = [("WORSCR", "worscr.a", "A", ["MODELA"]), ("WORSCR", "worscr.a", "B", []),
              ("WORSCR", "worscr.a", "B soft", ["SOFTDIV"]),
              ("MODSND", "modsnd_a.a", "A", []), ("MODSND", "modsnd_b.a", "B", []),
              ("DSPNYM", "dspnym_a.a", "A", []), ("DSPNYM", "dspnym_b.a", "B", [])]
    rows = []
    for routine, src, model, defs in builds:
        rng = random.Random(a.seed)
        random.seed(a.seed)
        code, labels, lst = assemble(src, "%s_%s" % (routine.lower(), model.replace(" ", "_")), defs)
        rig = Rig(ref, model[0], code, labels, lst)
        rig.pokey = pokey
        size09 = len(code) - (0x204 if routine == "MODSND" else 0)
        c65, c09, fails = [], [], []
        if routine == "WORSCR":
            for arc, vr, ra, rx, ry in cases_worscr(rng, a.n):
                inimat(mb)
                x, y_, diffs, cfg = rig.case(where["WORSCR"], "WORSCR", arc, vr, ra, rx, ry, pokey,
                                            compare_skip=())
                if diffs:
                    fails.append(diffs[:6])
                    break
                c65.append(x)
                c09.append(y_)
        elif routine == "MODSND":
            for arc, vr, ra, rx, ry in cases_modsnd(rng, a.n):
                x, y_, diffs, cfg = rig.case(where["MODSND"], "MODSND", arc, vr, ra, rx, ry, pokey)
                if diffs:
                    fails.append(diffs[:6])
                    break
                c65.append(x)
                c09.append(y_)
            p65, p09, pf = sound_sequence(rig, where["FSNDON"], where["MODSND"], rng, 5000)
            fails += pf
            play = (statistics.mean(p65), statistics.mean(p09)) if p65 else None
        else:
            for arc, vr, ra, rx, ry in cases_dspnym(rng, a.n):
                x, y_, diffs, cfg = rig.case(where["DSPNYM"], "DSPNYM", arc, vr, ra, rx, ry, pokey)
                if diffs:
                    fails.append(diffs[:6])
                    break
                c65.append(x)
                c09.append(y_)
        ok = not fails
        row = dict(routine=routine, model=model, size65=size65[routine], size09=size09,
                   cases=len(c65), ok=ok, fails=fails, checked=len(rig.checked))
        if c65:
            row["s65"], row["s09"] = summary(c65, c09)
        if routine == "MODSND" and ok:
            row["play"] = play
        rows.append(row)

    print("Rev 3 addresses: " + ", ".join("%s $%04X" % (k, where[k]) for k in
                                           ("WORSCR", "MODSND", "FSNDON", "DSPNYM", "VGSTAT", "VGYAB1")))
    print()
    print("%-7s %-7s %6s %6s %5s  %-24s %-24s %6s %6s  %s" % (
        "routine", "model", "6502 B", "6809 B", "ratio", "6502 cyc min/med/max", "6809 cyc min/med/max",
        "c ratio", "speed", "cases"))
    for r in rows:
        if "s65" not in r:
            print("%-7s %-7s FAILED before any case passed: %s" % (r["routine"], r["model"], r["fails"]))
            continue
        s65, s09 = r["s65"], r["s09"]
        speed = (s65[2] / MHZ_6502) / (s09[2] / MHZ_6809)
        print("%-7s %-7s %6d %6d %5.2f  %5d/%6.0f/%6d     %5d/%6.0f/%6d    %6.2f %5.1fx  %d%s" % (
            r["routine"], r["model"], r["size65"], r["size09"], r["size09"] / r["size65"],
            s65[0], s65[1], s65[3], s09[0], s09[1], s09[3], s09[2] / s65[2], speed, r["cases"],
            "" if r["ok"] else "  FAIL"))
        if r.get("play"):
            p65, p09 = r["play"]
            print("%-7s %-7s   playing the game's sounds, 5,000 IRQs: mean %0.f / %.0f cycles" % (
                "", "", p65, p09))
        for f in r["fails"]:
            print("    ", f)
        print("%-7s %-7s   %d instruction cycle counts checked against the lwasm listing" % (
            "", "", r["checked"]))
    if not all(r["ok"] for r in rows):
        sys.exit(1)


if __name__ == "__main__":
    main()
